# run on container environment
sudo: false

services:
  - mysql

language: php

cache:
  apt: true
  directories:
    - $HOME/.npm
    - vendor
    - $HOME/.composer/cache
    - tests/cache

notifications:
  email:
    on_success: change
    on_failure: always

php:
  - 7.3
  - 7.0

env:
  # WP pre-Gutenberg:
  - WP_VERSION=4.9
  # WP latest stable:
  - WP_VERSION=*
  # WP nightly:
  - WP_VERSION=dev-nightly

matrix:
  fast_finish: true

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi

install:
  - travis_retry composer install --no-suggest
  - travis_retry composer require --dev --update-with-dependencies --no-suggest roots/wordpress="${WP_VERSION} || *" wp-phpunit/wp-phpunit="${WP_VERSION} || *"

script:
  - composer test
